1. Tensors in PyTorch

In [1]:
#PyTorch to build a simple neural network
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import torch

import helper

In [2]:
#How we work with Pytorch tensors

x = torch.rand(3, 2)
x

tensor([[0.0866, 0.0584],
        [0.5835, 0.4108],
        [0.2430, 0.2298]])

In [3]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
z = x + y
z

tensor([[1.0866, 1.0584],
        [1.5835, 1.4108],
        [1.2430, 1.2298]])

In [5]:
z[0]

tensor([1.0866, 1.0584])

In [6]:
z[:, 1:]

tensor([[1.0584],
        [1.4108],
        [1.2298]])

In [7]:
# Return a new tensor z + 1
z.add(1)

tensor([[2.0866, 2.0584],
        [2.5835, 2.4108],
        [2.2430, 2.2298]])

In [8]:
# z tensor is unchanged
z

tensor([[1.0866, 1.0584],
        [1.5835, 1.4108],
        [1.2430, 1.2298]])

In [9]:
# Add 1 and update z tensor in-place
z.add_(1)

tensor([[2.0866, 2.0584],
        [2.5835, 2.4108],
        [2.2430, 2.2298]])

In [10]:
# z has been updated
z

tensor([[2.0866, 2.0584],
        [2.5835, 2.4108],
        [2.2430, 2.2298]])

Reshaping tensors

In [11]:
z.size()

torch.Size([3, 2])

In [12]:
z.resize_(2, 3)

tensor([[2.0866, 2.0584, 2.5835],
        [2.4108, 2.2430, 2.2298]])

In [13]:
z

tensor([[2.0866, 2.0584, 2.5835],
        [2.4108, 2.2430, 2.2298]])

  Numpy to Torch and back

In [14]:
a = np.random.rand(4,3)
a

array([[0.37379527, 0.27903002, 0.83249437],
       [0.5894335 , 0.66240127, 0.88431356],
       [0.84670379, 0.69581553, 0.01875448],
       [0.41629101, 0.63766821, 0.44361056]])

In [15]:
b = torch.from_numpy(a)
b

tensor([[0.3738, 0.2790, 0.8325],
        [0.5894, 0.6624, 0.8843],
        [0.8467, 0.6958, 0.0188],
        [0.4163, 0.6377, 0.4436]], dtype=torch.float64)

In [16]:
b.numpy()

array([[0.37379527, 0.27903002, 0.83249437],
       [0.5894335 , 0.66240127, 0.88431356],
       [0.84670379, 0.69581553, 0.01875448],
       [0.41629101, 0.63766821, 0.44361056]])

In [17]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.7476, 0.5581, 1.6650],
        [1.1789, 1.3248, 1.7686],
        [1.6934, 1.3916, 0.0375],
        [0.8326, 1.2753, 0.8872]], dtype=torch.float64)

In [18]:
# Numpy array matches new values from Tensor
a

array([[0.74759054, 0.55806004, 1.66498875],
       [1.17886699, 1.32480253, 1.76862711],
       [1.69340759, 1.39163107, 0.03750896],
       [0.83258202, 1.27533642, 0.88722112]])